package cursoJava.ejerciciosResueltos.metodos.constructor;
/**
 * 
 * @author cursoJava
 * 
 * 3 - PLANTEAR UNA CLASE TABLA DE MULTIPLICAR, DEFINIR DOS CONSTRUCTORES UNO CON UN PARAMETRO QUE LLEGUE UN ENTERO 
 *     INDICANDO QUE TABLA QUEREMOS VER, Y OTRO CON DOS PARAMETROS ENTEROS QUE INDIQUE EL PRIMERO QUE TABLA QUEREMOS VER Y 
 *     EL SEGUNDO PARAMETRO INDICA CUANTOS TERMINOS MOSTRAR. SINO LLEGA LA CANTIDAD DE TERMINOS A MOSTRAR INICIALIZAR EN
 *     10 LOS TERMINOS A MOSTRAR.
 *
 */
public class TablaMultiplicar {

}
