package cursoJava.ejerciciosResueltos.arrays;
/**
 * 
 * @author cursoJava
 * 
 *  6 - SE TIENEN LAS NOTAS DEL PRIMER PARCIAL DE LOS ALUNNOS DE LOS CURSOS, EL CURSOA A Y EL CURSO B, CADA CURSO
 *      CUENTA CON 5 ALUNNOS. REALIZAR UN PROGRMAMA QUE MUESTRE EL CURSO QUE OBTUVO EL MAYOR PROMEDIO GENERAL.
 *      
 *      NOTA : APARTIR DE ESTE EJERCICIOS APLICAREMOS PROGRAMACION ORIENTADA A OBJETOS.
 *
 */

public class PruebaVector6 {
	// PROPIEDADES DE LA CLASE.
	int[] cursoA;
	int[] cursoB;

	// METODO PRINCIPAL DE LA CLASE, ACA SE CREA EL OBJETO D ELA CLASE Y SE EJECUTAN TODOS LOS METODOS.
	public static void main(String[] args) {
		// CREAMOS OBJETO DE LA CLASE PruebaVector6
		

	}
	
	
	// METODO QUE PERMITE CREAR VENTANA DE DIALOGO PARA EL INGRESO DE DATA.
	public void getCreateVentana() {
		
	}
	
	
	// METODO QUE PERMITE CALCULAR EL PROMEDIO GENERAL.
	public void getCalcularPromedios() {}

}
