package cursoJava.condicionales.aninadas;

/**
 * 
 * @author cursoJava
 * 
 * 5 - UN POSTULANTE A UN EMPLEO, REALIZA UN TEST DE CAPACITACION, SE OBTUVO LA SIGUIENTE INFORMACION: CANTIDAD TOTAL DE PREGUNTAS
	    QUE SE REALIZARON Y LA CANTIDAD DE PREGUNTAS QUE CONTESTO CORRECTAMENTE. SE PIDE CONFECCIONAR UN PROGRAMA QUE INGRESE LOS
	    DOS DATOS POR TECLADO E INFORMAR EL NIVEL DEL MISMO SEGUN EL PORCENTAJE DE RESPUESTAS CORRECTAS QUE SE HA OBTENIDO 
	    SABIENDO QUE: NIVEL MAXIMO Porcentaje>=90% NIVEL MEDIO Porcentaje>=75% y <90% NIVEL REGULAR Porcentaje>=50% y <75% 
	    FUERA DE NIVEL Porcentaje<50%
 *
 */

public class EjerciciosCondicionalAnidada5 {

}
