package cursoJava.historiaJava;


public class HistoriaJava {
	
 /**
  * **********************************************************************************************************************
  * HISTORIA JAVA : 
  * 
  * JAVA ES UN LENGUAJE DE PROGRAMACION ORIENTADO A OBJETO, CREADDO POR "SUN MICROSYSTEMS" ESTE LENGUAJE FUE 
  * CREADO POR PATRICK NEWTON Y JAMES GOSLING EN 1991, ESTE LENGUAJE SE CREO ORIGINALMENTE ORIENTADO A ELECTRODOMESTICOS.
  * 
  * JAVA, COMO LENGUAJE DE PROGRAMCION, SE INTRODUJO A FINALES DE 1995. LA CLAVE FUE LA INCORPORACION DE UN INTERPRETE 
  * JAVA EN EL PROGRAMA NETSCAPE NAVIGATOR, VERSION 2.0, PRODUCIENDO UNA VERDADERA REVOLUCION EN INTERNET. JAVA 1.1 
  * APARECIO A PRICIPIOS DE 1997, MEJORANDO SUSTANCIALMENTE LA PRIMERA VERSION DEL LENGUAJE, ACTUALMENTE JAVA SE ENCUENTRA
  * EN LA VERSION 11.
  * 
  * NOTA : AL PROGRAMAR EN JAVA NO SE PARTE DE CERO. CUALQUIER APLICACION QUE SE DESARROLLE EN JAVA "CUELGA (0 SE APOYA, 
  * SEGUN COMO SE QUIERA VER) EN UN GRAN NUMERO DE CLASES PREEXISTENTES. ALGUNAS DE ELLAS LAS HA PODIOD HACER EL PROPIO 
  * USUARIO, OTRAS PUEDEN SER COMERCIALES, PERO SIEMPRE HAY UN NUMERO MUY IMPORTANTES DE CLASES QUE FORMAN PARTE DEL 
  * PROPIO LENGUAJE. INGRESA EN  https://docs.oracle.com/javase/7/docs/api/ PARA VISUALIZAR LA API DE JAVA.
  * **********************************************************************************************************************
  * **********************************************************************************************************************
  *	CARACTERISTICAS DE JAVA : 
  *
  * A CONTINUACION DE INCLUYE UNA LISTA DE LAS CARACTERISTICAS MAS INPORTANTES DEL LENGUAJE JAVA.
  *
  * SIMPLE : JAVA ES MUY FACIL DE APRENDER Y SU SINTAXIS ES SIMPLE, LIMPIA Y FACIL DE ENTENDER. SEGUN SUN, EL LENGUAJE JAVA ES UN
  * LENGUAJE DE PROGRAMACION SIMPLE PORQUE LA SINTAXIS DE JAVA SE BASA EN C++ (POR LO QUE ES MAS FACIL PARA LOS PROGRAMADORES
  * APRENDERLA DESPUES DE C++) JAVA HA ELIMANDO MUCHAS CARATERISTICAS COMPLICADAS Y POCO UTILIZADAS, POR EJEMPLO PUNTEROS
  * EXPLICITOS, SOBRE CARGA DE CONSTRUCTORES, NO ES NECESARIO ELIMINAR OBJETOS SIN REFERENCI PORQUE HAY UNA RECOLECCION AUTOMATICA
  * DE BASURA EN JAVA.
  * 
  * ORIENTADO A OBJETO :
  * 
  * 

 **/
	


}
