package cursoJava.condicionales.aninadas;
/**
 * 
 * @author cursoJava
 * 
 *  1 - CONFECCIONAR UN PROGRAMA QUE PIDA POR TECLADO TRES NOTAS DE UN ALUNNO, CALCULE EL PROMEDIO E IMPRIMA ALGUNO DE ESTOS 
        MENSAJES : SI EL PROMEDIO ES MAYOR O IGUAL A 7 MOSTRAR "PROMOCIONADO", SI EL PROMEDIO ES MAYOR O IGUAL A 4 Y MENOR QUE 7
        MOSTRAR "REGULAR" SI EL PROMEDIO ES MENOR A 4 MOSTRAR "REPROBADO".
 *
 */
public class EjerciciosCondicionalAnidada1 {

}
