package cursoJava.condicionales.simples;

/**
 * 
 * @author cursoJava
 * 
 *  5 - SE INGRESA POR TECLADO UN NUMERO POSOTIVO DE UNO O DOS DIGITOS(1..99) MOSTRAR UN MENSAJE INDICANDO SI EL NUMERO TIENE UNO O
        DOS DIGITOS (TENER EN CUENTA QUE CONDICION DEBE CUMPLIRSE PARA TENER DOS DIGITOS. "UN NUMERO ENTERO").
 *
 */
public class EjercicioCondicionalSimple5 {

}
