package cursoJava.bucles.DoWhile;

/**
 * 
 * @author cursoJava
 * 
 * 3 - REALIZAR UN PROGRAMA QUE PERMITA INGRESAR EL PESO (EN KG) DE PIEZAS, EL PROCESO TERMINA CUANDO INGRESEMOS EL
 *     VALOR CERO, DEBE INFORMAR, CUANTAS PIEZAS TIENEN PESOS ENTRE 9.8 KG Y 10.2KG, CUANTAS CON MAS DE 10.2KG Y
 *     CUANTAS CON MENOS DE 9,8KG, LA CANTIDAD TOTAL DE PIEZAS PROCESADAS.
 *
 */

public class EjerciciosBucleDoWhile3 {

}
