package cursoJava.bucles.DoWhile;

/**
 * 
 * @author cursoJava
 * 
 * 4 - REALIZAR UN PROGRAMA QUE ACOMULE(SUME) VALORES INGRESAODS POR TECLADO HASTA INGRESAR EL 999 (NO SUMAR DICHO
 *     VALOR INDICAR QUE HA FINALIZADO LA CARGA). IMPRIMIR EL VALOR ACOMULADO E INFORMAR SI DICHO VALOR ES CERO,
 *     MAYOR A CERO O MENOR A CERO.
 *
 */
public class EjerciciosBucleDoWhile4 {

}
