package cursoJava.tipoDatos;
/**
 * 
 * @author cursoJava
 * 
 * 2 . REALIZAR LA CARGA DEL LADO DE UN CUADRADO, MOSTRAR POR PANTALLA EL PERIMETRO DEL MISMO (EL PERIMETRO DE UN CUADRADO SE
   CALCULA MULTIPLICANDO EL VALOR DEL LADO POR CUATRO)
 *
 */

public class EjerciciosTiposDatos2 {

}
