package cursoJava.operadores;
/**
 * 
 * @author cursoJava
 * 
 *   8 - DE UN OPERARIO SE CONOCE SU SUELDO Y LOS AÑOS DE ANTIGUEDAD. SE PIDE CONFECCIONAR UN PROGRAMA QUE LEA LOS DATOS DE
	 *      ENTRADA E INFORME: A) SI EL SUELDO ES INFERIOR A 500 Y SU ANTIGUEDAD ES IGUAL O SUPERIOR A 10 AÑOS, OTORGARLE UN
	 *      AUMENTO DE 20%, MOSTRAR EL SUELDO A PAGAR. B) SI EL SUELDO ES INFERIOR A 500 PERO SU ANTIGUEDAD ES MENOR A 10 AÑOS
	 *      OTORGARLE UN AUMENTO DE 5% C) SI EL SUELDO ES MAYOR O IGUAL A 500 MOSTRAR EL SUELDO EN PANTALLA SIN CAMABIOS.
 *
 */
public class EjerciciosOperadores8 {

}
