package cursoJava.ejerciciosResueltos.poo.herencia;

/**
 * 
 * @author cursoJava
 * 
 *         IMPLEMENTAR DOS CLASE QUE LLAMAREMOS SUMA Y RESTA. CADA CLASE TIENE
 *         COMO ATRIBUTO VARLO1, VALOR2 Y RESULTADO. LOS METODOS A DEFINIR SON
 *         CARGAR1 (QUE INICIALIZA EL ATRIBUTO VALOR1), CARGAR2 (QUE INICIALIZA
 *         EL ATRIBUTO VALOR2), OPERAR (QUE EN EL CASO DE LA CLASE SUMA SUMA LOS
 *         DOS ATRIBUTOS Y EN EL CASO DE LA CLASE RESTA HAGA LA REFERENCIA ENTRE
 *         EL VALOR1 Y VALOR2, Y OTRO METODO MOSTRARRESULTADO)
 *
 */

public class Suma extends Operacion {

	// METODO QUE PERMITE REALIZAR OPERACIONES ARITMETICAS DE SUMA Y RESTA.
	public void operar() {
		resultado = valor1 + valor2;
	}

}
